name: Lint, Validate, Preview, and Deploy
on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Azure Login using Managed Identity via OIDC
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 2) Lint Bicep template
      - name: Lint Bicep
        run: |
          echo "Running Bicep Linter..."
          az bicep build --file storage.bicep

      # 3) Validate template
      - name: Validate Template
        run: |
          RG_NAME="rg-central-india"
          echo "Validating deployment..."
          az deployment group validate \
            --resource-group "$RG_NAME" \
            --template-file storage.bicep \
            --parameters @parameters.prod.json

      # 4) Preview changes (What-If)
      - name: Preview Deployment (What-If)
        run: |
          RG_NAME="rg-central-india"
          echo "Previewing changes..."
          az deployment group what-if \
            --resource-group "$RG_NAME" \
            --template-file storage.bicep \
            --parameters @parameters.prod.json

      # 5) Deploy template
      - name: Deploy Template
        run: |
          RG_NAME="rg-central-india"
          echo "Deploying resources..."
          az deployment group create \
            --resource-group "$RG_NAME" \
            --template-file storage.bicep \
            --parameters @parameters.prod.json

      # 6) Create a user via Microsoft Graph
      - name: Create User
        run: |
          GRAPH_TOKEN=$(az account get-access-token --resource https://graph.microsoft.com --query accessToken -o tsv)
          echo "GRAPH_TOKEN=$GRAPH_TOKEN" >> $GITHUB_ENV
          curl -X POST https://graph.microsoft.com/v1.0/users \
            -H "Authorization: Bearer $GRAPH_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "accountEnabled": true,
              "displayName": "Demo User",
              "mailNickname": "demouser",
              "userPrincipalName": "demouser@<tenant>.onmicrosoft.com",
              "passwordProfile": {
                "forceChangePasswordNextSignIn": false,
                "password": "Pa55w.rd1234"
              }
            }'