name: Deploy Storage and Manage Users
on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Get GitHub OIDC token and store it
      - name: Get GitHub OIDC Token
        id: oidc
        run: |
          echo "GITHUB_OIDC_TOKEN=${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" >> $GITHUB_ENV
          echo "OIDC_REQUEST_URL=${ACTIONS_ID_TOKEN_REQUEST_URL}" >> $GITHUB_ENV
        env:
          ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ github.token }}
          ACTIONS_ID_TOKEN_REQUEST_URL: ${{ github.api_url }}/actions/oidc/token

      # 2) Login using Managed Identity via OIDC
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 3) Store Azure token
      - name: Get Azure Token
        run: |
          AZURE_TOKEN=$(az account get-access-token --resource https://management.azure.com --query accessToken -o tsv)
          echo "AZURE_TOKEN=$AZURE_TOKEN" >> $GITHUB_ENV

      # 4) Deploy Storage Account using Bicep
      - name: Deploy Storage Account
        run: |
          RG_NAME="rg-central-india"
          az group create --name "$RG_NAME" --location "centralindia"
          az deployment group create \
            --resource-group "$RG_NAME" \
            --template-file storage.bicep \
            --parameters @parameters.prod.json

      # 5) Create a user via Microsoft Graph
      - name: Create User
        run: |
          GRAPH_TOKEN=$(az account get-access-token --resource https://graph.microsoft.com --query accessToken -o tsv)
          echo "GRAPH_TOKEN=$GRAPH_TOKEN" >> $GITHUB_ENV
          curl -X POST https://graph.microsoft.com/v1.0/users \
            -H "Authorization: Bearer $GRAPH_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "accountEnabled": true,
              "displayName": "Demo User",
              "mailNickname": "demouser",
              "userPrincipalName": "demouser@<tenant>.onmicrosoft.com",
              "passwordProfile": {
                "forceChangePasswordNextSignIn": false,
                "password": "Pa55w.rd1234"
              }
            }'