name: Deploy Infra

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build (lint) the Bicep to catch syntax issues early
      - name: Bicep build (lint)
        uses: azure/cli@v1
        with:
          inlineScript: |
            az --version
            az bicep build --file ./deploy/main.bicep
            echo "Bicep build OK"

  validate:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # (Optional) Show OIDC token claims minted by GitHub so you can confirm 'sub' = repo:<org>/<repo>:ref:refs/heads/main
      - name: Show OIDC token claims (debug only)
        shell: bash
        run: |
          set -e
          RAW=$(curl -sSL "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange" \
                 -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN")
          JWT=$(echo "$RAW" | jq -r '.value')
          # Decode payload (handle base64url padding)
          PAYLOAD=$(echo "$JWT" | cut -d '.' -f2 | tr '_-' '/+' \
                    | awk '{ l=4-(length%4); if(l<4){printf "%s", $0; for(i=0;i<l;i++) printf "=" } else printf "%s", $0 }' \
                    | base64 -d 2>/dev/null || true)
          echo "$PAYLOAD" | jq .

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Validate the template & parameters against the RG scope
      - name: Validate template (group scope)
        uses: azure/cli@v1
        with:
          inlineScript: |
            az deployment group validate \
              --resource-group ${{ secrets.AZURE_RG_NAME }} \
              --template-file ./deploy/main.bicep \
              --parameters @./deploy/parameters.prod.json

  preview:
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: What-if (preview the changes)
        uses: azure/cli@v1
        with:
          inlineScript: |
            az deployment group what-if \
              --resource-group ${{ secrets.AZURE_RG_NAME }} \
              --template-file ./deploy/main.bicep \
              --parameters @./deploy/parameters.prod.json

  deploy:
    needs: preview
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy (group scope)
        uses: azure/cli@v1
        with:
          inlineScript: |
            az deployment group create \
              --name ${{ github.run_number }} \
              --resource-group ${{ secrets.AZURE_RG_NAME }} \
              --template-file ./deploy/main.bicep \
              --parameters @./deploy/parameters.prod.json